name: CI

on:
  push:
    branches: [main, master]
    tags: ["*"]
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
      - Cargo.toml
      - Cargo.lock
      - go.mod
      - go.sum
      - package.json
      - package-lock.json
      - tree-sitter.json
      - .github/workflows/**
  pull_request:
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
      - Cargo.toml
      - Cargo.lock
      - go.mod
      - go.sum
      - package.json
      - package-lock.json
      - tree-sitter.json
      - .github/workflows/**

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test parser
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@49f8c1f20b60102eae8c033bb7c7f6cd056f6086 # v2

      - name: Check version consistency
        run: ./scripts/check-versions.sh

      - name: Run tests
        uses: tree-sitter/parser-test-action@05f6ce7c7e54603c45cd87ed926725dc870bcc63 # v3
        with:
          test-go: true
          test-rust: true
          test-node: true
